### ISSUE TITLE
Error with cupy compiling cuda kernel

### ISSUE THREAD

**Issue by ShaoxiongYao** [mortacious/cupy-knn#3]
Hi,

First thank you providing this library! I tried to `pip` install the package but unfortunately I was not able to run it on my Linux machine. The error I get when running a testing script was:

```
Traceback (most recent call last):
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 689, in compile
    nvrtc.compileProgram(self.ptr, options)
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 159, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 171, in cupy_backends.cuda.libs.nvrtc.compileProgram
  File "cupy_backends/cuda/libs/nvrtc.pyx", line 89, in cupy_backends.cuda.libs.nvrtc.check_status
cupy_backends.cuda.libs.nvrtc.NVRTCError: NVRTC_ERROR_COMPILATION (6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "script_check_valid.py", line 5, in <module>
    lbvh = LBVHIndex()
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy_knn/lbvh_index.py", line 73, in __init__
    self._compute_morton_kernel_float = _construct_tree_kernels.get_function('compute_morton_kernel')
  File "cupy/_core/raw.pyx", line 470, in cupy._core.raw.RawModule.get_function
  File "cupy/_core/raw.pyx", line 394, in cupy._core.raw.RawModule.module.__get__
  File "cupy/_core/raw.pyx", line 402, in cupy._core.raw.RawModule._module
  File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "cupy/_core/raw.pyx", line 547, in cupy._core.raw._get_raw_module
  File "cupy/_core/core.pyx", line 2172, in cupy._core.core.compile_with_cache
  File "cupy/_core/core.pyx", line 2235, in cupy._core.core.compile_with_cache
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 496, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 574, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 322, in compile_using_nvrtc
    return _compile(source, options, cu_path,
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 306, in _compile
    compiled_obj, mapping = prog.compile(options, log_stream)
  File "/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy/cuda/compiler.py", line 708, in compile
    raise CompileException(log, self.src, self.name, options,
cupy.cuda.compiler.CompileException: /usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(211): error: identifier "__CHAR_BIT__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(312): error: identifier "__FLT_MANT_DIG__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(313): error: identifier "__FLT_DIG__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(321): error: identifier "__FLT_RADIX__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(325): error: identifier "__FLT_MIN_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(326): error: identifier "__FLT_MIN_10_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(327): error: identifier "__FLT_MAX_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(328): error: identifier "__FLT_MAX_10_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(315): error: identifier "__FLT_MIN__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(316): error: identifier "__FLT_MAX__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(322): error: identifier "__FLT_EPSILON__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(336): error: identifier "__builtin_huge_valf" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(337): error: identifier "__builtin_nanf" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(338): error: identifier "__builtin_nansf" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(344): error: identifier "__FLT_DENORM_MIN__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(364): error: identifier "__DBL_MANT_DIG__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(365): error: identifier "__DBL_DIG__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(373): error: identifier "__FLT_RADIX__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(377): error: identifier "__DBL_MIN_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(378): error: identifier "__DBL_MIN_10_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(379): error: identifier "__DBL_MAX_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(380): error: identifier "__DBL_MAX_10_EXP__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(367): error: identifier "__DBL_MIN__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(368): error: identifier "__DBL_MAX__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(374): error: identifier "__DBL_EPSILON__" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(388): error: identifier "__builtin_huge_val" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(389): error: identifier "__builtin_nan" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(390): error: identifier "__builtin_nans" is undefined

/usr/local/cuda/include/cuda/std/detail/libcxx/include/limits(396): error: identifier "__DBL_DENORM_MIN__" is undefined

/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy_knn/cuda/lbvh.cuh(41): error: identifier "UINT_MAX" is undefined

/home/motion/cupy-knn/env/lib/python3.8/site-packages/cupy_knn/cuda/lbvh.cuh(133): error: identifier "UINT_MAX" is undefined

/tmp/tmp9l76mutn/8021971f983924d3c55c5a8b9997c0d1fb55f321.cubin.cu(40): error: identifier "UINT_MAX" is undefined

/tmp/tmp9l76mutn/8021971f983924d3c55c5a8b9997c0d1fb55f321.cubin.cu(50): error: identifier "UINT_MAX" is undefined

/tmp/tmp9l76mutn/8021971f983924d3c55c5a8b9997c0d1fb55f321.cubin.cu(116): error: identifier "UINT_MAX" is undefined

/tmp/tmp9l76mutn/8021971f983924d3c55c5a8b9997c0d1fb55f321.cubin.cu(226): error: identifier "UINT_MAX" is undefined

35 errors detected in the compilation of "/tmp/tmp9l76mutn/8021971f983924d3c55c5a8b9997c0d1fb55f321.cubin.cu".
```

I looked at the cupy library to see if there has been a similar error report, but found this problem may be more relevant to my own C++ environment set up. If you may have time taking a look at this problem, I will appreciate your help!

**Comment by mortacious** [comment]
This is most likely a problem with your CUDA installation or a problem in `cupy`. You can try if it works in a separate `conda` environment with it's own independent`cupy` and `cudatoolkit`versions.
